model:
  latent_dim: 128
  channels: 64

diffusion:
  steps: 1000
  schedule: cosine

train:
  batch_size: 16
  lr: 1e-4


# defaults:
#   - model: vae
#   - diffusion: unet_base
#   - data: dataset
#   - train: default
